// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService handles library management, imports, index db and asset streaming
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseLibrary unloads the currently active library
 */
export function CloseLibrary(): $CancellablePromise<void> {
    return $Call.ByID(2801298557);
}

/**
 * CreateLibrary creates a new library directory ending in .library and initializes libSQL database
 */
export function CreateLibrary(parentDir: string, libName: string): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(1201938221, parentDir, libName);
}

/**
 * DeleteItem removes an item from disk and deletes its row from libSQL
 */
export function DeleteItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(967795986, id);
}

/**
 * GetActiveLibrary returns the currently active library or nil if none open
 */
export function GetActiveLibrary(): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(3406680183);
}

/**
 * GetAssetServerPort returns the dynamic port for asset serving
 */
export function GetAssetServerPort(): $CancellablePromise<number> {
    return $Call.ByID(773365530);
}

/**
 * GetItem retrieves a single item by ID
 */
export function GetItem(id: string): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(493017265, id);
}

/**
 * GetItems queries items from libSQL index database
 */
export function GetItems(query: string, sortOrder: string): $CancellablePromise<$models.Item[] | null> {
    return $Call.ByID(77281638, query, sortOrder);
}

/**
 * ImportFiles imports a list of file or folder paths into the library.
 * All files are physically copied into their own dedicated subdirectories, isolated from the original sources.
 */
export function ImportFiles(sourcePaths: string[] | null): $CancellablePromise<$models.Item[] | null> {
    return $Call.ByID(726300234, sourcePaths);
}

/**
 * ImportFromBase64 imports image or binary data from browser drag-drop or clipboard paste
 */
export function ImportFromBase64(filename: string, base64Data: string): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(1565957016, filename, base64Data);
}

/**
 * OpenLibrary opens an existing library at libraryPath
 */
export function OpenLibrary(libraryPath: string): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(2423459937, libraryPath);
}

/**
 * RevealInFinder opens macOS Finder or Windows Explorer highlighting the item file
 */
export function RevealInFinder(id: string): $CancellablePromise<void> {
    return $Call.ByID(2477790360, id);
}

/**
 * SelectDirectory opens native system dialog to pick a target directory
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2456625565);
}

/**
 * SelectLibraryDialog opens native system dialog to pick an existing .library folder
 */
export function SelectLibraryDialog(): $CancellablePromise<string> {
    return $Call.ByID(186540445);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2038771421, app);
}
