// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item represents a single managed asset in the library
 */
export interface Item {
    "id": string;
    "name": string;
    "extension": string;
    "filename": string;
    "size": number;
    "mimeType": string;
    "width": number;
    "height": number;
    "hasThumbnail": boolean;
    "tags": string[] | null;
    "createdAt": number;
    "importedAt": number;

    /**
     * local disk path of item directory
     */
    "itemPath": string;

    /**
     * HTTP stream URL
     */
    "originalUrl": string;

    /**
     * HTTP thumbnail URL
     */
    "thumbnailUrl": string;

    /**
     * HTTP download URL for OS drag-out
     */
    "downloadUrl": string;
}

/**
 * LibraryInfo represents metadata about an opened library
 */
export interface LibraryInfo {
    "id": string;
    "name": string;
    "path": string;
    "createdAt": number;
    "itemCount": number;
}
