// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item represents a single managed asset in the library.
 */
export interface Item {
    "id": string;

    /**
     * uppercase content hash (SHA-256)
     */
    "hex": string;
    "name": string;
    "extension": string;
    "filename": string;
    "size": number;
    "mimeType": string;
    "width": number;
    "height": number;
    "hasThumbnail": boolean;
    "tags": string[] | null;
    "createdAt": number;
    "importedAt": number;

    /**
     * local disk path of item directory (items/<HEX>)
     */
    "itemPath": string;

    /**
     * absolute local path to physical file
     */
    "filePath": string;

    /**
     * shell-escaped path with backslash spaces
     */
    "shellPath": string;

    /**
     * file:// URI with spaces %20-encoded
     */
    "fileUrl": string;

    /**
     * HTTP stream URL
     */
    "originalUrl": string;

    /**
     * HTTP thumbnail URL
     */
    "thumbnailUrl": string;

    /**
     * HTTP download URL for OS drag-out
     */
    "downloadUrl": string;
}

/**
 * LibraryInfo represents metadata about an opened library.
 */
export interface LibraryInfo {
    "id": string;
    "name": string;
    "path": string;
    "createdAt": number;
    "itemCount": number;
}

/**
 * LibraryManager coordinates library lifecycle, storage, libSQL indexing, and user data.
 */
export interface LibraryManager {
}
