// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppMenuItem is one row of the application menu.
 * 
 * A row with Separator set is a divider: every other field is meaningless.
 */
export interface AppMenuItem {
    /**
     * Action is the command identity (one of the AppMenuAction constants).
     */
    "action": string;

    /**
     * Title is the canonical English label. The native macOS menu bar uses it
     * directly; the frontend prefers the translation behind LabelKey and falls
     * back to Title.
     */
    "title": string;

    /**
     * LabelKey is the frontend i18n key (frontend/src/messages/*.json).
     */
    "labelKey": string;

    /**
     * Icon is one of the AppMenuIcon values.
     */
    "icon": string;

    /**
     * Shortcut is the platform-specific, human-readable accelerator shown to the
     * user: "Ctrl+I" on Windows/Linux, "⌘," on macOS.
     */
    "shortcut": string;

    /**
     * Separator marks a non-interactive divider row.
     */
    "separator"?: boolean;

    /**
     * Destructive styles the row as dangerous (used by Quit).
     */
    "destructive"?: boolean;
}

/**
 * Folder represents a virtual organizational directory in the library.
 */
export interface Folder {
    "id": string;
    "name": string;
    "parentId": string;
    "createdAt": number;
    "sortOrder": number;
    "children"?: Folder[] | null;
    "itemCount": number;
}

/**
 * Item represents a single managed asset in the library.
 */
export interface Item {
    "id": string;

    /**
     * uppercase content hash (SHA-256)
     */
    "hex": string;
    "name": string;
    "extension": string;
    "filename": string;
    "size": number;
    "mimeType": string;
    "width": number;
    "height": number;
    "hasThumbnail": boolean;
    "tags": string[] | null;
    "folders": string[] | null;
    "inTrash": boolean;
    "trashedAt": number;
    "createdAt": number;
    "importedAt": number;

    /**
     * local disk path of item directory (items/<HEX>)
     */
    "itemPath": string;

    /**
     * absolute local path to physical file
     */
    "filePath": string;

    /**
     * shell-escaped path with backslash spaces
     */
    "shellPath": string;

    /**
     * file:// URI with spaces %20-encoded
     */
    "fileUrl": string;

    /**
     * HTTP stream URL
     */
    "originalUrl": string;

    /**
     * HTTP thumbnail URL
     */
    "thumbnailUrl": string;

    /**
     * HTTP download URL for OS drag-out
     */
    "downloadUrl": string;
}

/**
 * LibraryInfo represents metadata about an opened library.
 */
export interface LibraryInfo {
    "id": string;
    "name": string;
    "path": string;
    "createdAt": number;
    "itemCount": number;
}

/**
 * LibraryManager coordinates library lifecycle, storage, libSQL indexing, and user data.
 */
export interface LibraryManager {
}

/**
 * Tag represents a tag taxonomy entry with its item count.
 */
export interface Tag {
    "name": string;
    "createdAt": number;
    "itemCount": number;
}
