// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails RPC service exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddItemToFolder(itemID: string, folderID: string): $CancellablePromise<void> {
    return $Call.ByID(2158034121, itemID, folderID);
}

export function CloseLibrary(): $CancellablePromise<void> {
    return $Call.ByID(3049267163);
}

export function CreateFolder(name: string, parentID: string): $CancellablePromise<$models.Folder | null> {
    return $Call.ByID(1778465740, name, parentID);
}

export function CreateLibrary(parentDir: string, libName: string): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(3111065859, parentDir, libName);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(2706508003, id);
}

export function DeleteItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(4132191696, id);
}

export function GetActiveLibrary(): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(990194437);
}

export function GetAssetServerPort(): $CancellablePromise<number> {
    return $Call.ByID(1298596620);
}

export function GetFolders(): $CancellablePromise<$models.Folder[] | null> {
    return $Call.ByID(1769180301);
}

export function GetItem(id: string): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(2078610007, id);
}

export function GetItems(query: string, sortOrder: string): $CancellablePromise<$models.Item[] | null> {
    return $Call.ByID(765169324, query, sortOrder);
}

export function GetRecentLibraries(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2812002174);
}

export function ImportFiles(sourcePaths: string[] | null): $CancellablePromise<$models.Item[] | null> {
    return $Call.ByID(3027212300, sourcePaths);
}

export function ImportFromBase64(filename: string, base64Data: string): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(2134855510, filename, base64Data);
}

export function ImportFromURL(rawURL: string): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(780943642, rawURL);
}

export function OpenLibrary(libraryPath: string): $CancellablePromise<$models.LibraryInfo | null> {
    return $Call.ByID(2189258727, libraryPath);
}

export function RemoveItemFromFolder(itemID: string, folderID: string): $CancellablePromise<void> {
    return $Call.ByID(4055258539, itemID, folderID);
}

export function RenameFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2472567758, id, name);
}

export function RevealInFinder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1659303366, id);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3643486703);
}

export function SelectLibraryDialog(): $CancellablePromise<string> {
    return $Call.ByID(2272606043);
}

export function SetItemFolders(itemID: string, folderIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3134410356, itemID, folderIDs);
}

export function SetManager(mgr: $models.LibraryManager | null): $CancellablePromise<void> {
    return $Call.ByID(3918042731, mgr);
}

export function StartDrag(id: string): $CancellablePromise<void> {
    return $Call.ByID(1926602914, id);
}
